c_library(
    name = "stdlib",
    srcs = glob("*"),
    visibility = ["PUBLIC"],
    deps = [
        "//include/libc",
        "//src/libc/platform/include",
        "//src/libc/platform/functions/signal",
    ],
)
