c_library(
    name = "time",
    srcs = glob("*.c"),
    visibility = ["PUBLIC"],
    deps = [
        "//include/libc:assert",
        "//include/libc:stdint",
        "//include/libc:time",
        "//src/libc/platform/functions/_PDCLIB",
    ],
)
