plugin_repo(
    name = "shell",
    owner = "please-build",
    plugin = "shell-rules",
    revision = "v0.2.0",
)

plugin_repo(
    name = "cc",
    owner = "please-build",
    plugin = "cc-rules",
    revision = "v0.4.0",
)
