plugin_repo(
  name = "shell",
  revision = "v0.2.0",
  plugin = "shell-rules",
  owner = "please-build",
)
plugin_repo(
  name = "cc",
  revision = "v0.4.0",
  plugin = "cc-rules",
  owner = "please-build",
)
