c_library(
    name = "_PDCLIB",
    srcs = glob("*.c"),
    visibility = ["PUBLIC"],
    deps = [
        "//include/libc",
        "//include/kernel",
        "//src/libc/platform/include",
    ],
)