c_library(
    name = "stdio",
    srcs = glob(["*.c"]),
    deps = [
        "//include/libc",
        "//src/libc/platform/include",
        "//src/libc/_PDCLIB",
        "//src/libc/platform/functions/_PDCLIB",
    ],
    visibility = ["PUBLIC"],
)