c_library(
    name = "stdio",
    srcs = glob(["*.c"]),
    visibility = ["PUBLIC"],
    deps = [
        "//src/libc/_PDCLIB",
        "//src/libc/_dlmalloc",
        "//src/libc/platform/functions/_PDCLIB",
    ],
)
