c_library(
    name = "files",
    srcs = ["files.c"],
    hdrs = ["files.h"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/libc/stdlib",
        "//src/libc/string",
        "//src/serial",
    ],
)