c_library(
    name = "string",
    srcs = glob("*.c"),
    visibility = ["PUBLIC"],
    deps = [
        "//include/libc:string",
        "//include/libc/pdclib",
        "//src/libc/platform/functions/_PDCLIB",
        "//src/libc/stdlib",
    ],
)
