c_library(
    name = "_PDCLIB",
    srcs = glob("*.c"),
    visibility = ["PUBLIC"],
    deps = [
        "//include/libc",
        "//src/libc/ctype",
        "//src/libc/inttypes",
        "//src/libc/locale",
        "//src/libc/platform/include",
        "//src/libc/stdlib",
        "//src/libc/string",
    ],
)
